create table if not exists public.miniapp_consents (
  user_id uuid not null references auth.users(id) on delete cascade,
  policy_version text not null,
  accepted_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, policy_version)
);

create table if not exists public.miniapp_event_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id uuid not null references public.events(id) on delete cascade,
  template_id text not null,
  status text not null default 'accepted',
  send_at timestamptz,
  sent_at timestamptz,
  last_error text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, event_id, template_id),
  constraint miniapp_event_subscriptions_status_check
    check (status in ('accepted', 'rejected', 'sent', 'failed', 'cancelled'))
);

create index if not exists miniapp_event_subscriptions_due_idx
  on public.miniapp_event_subscriptions (status, send_at)
  where status = 'accepted';

create table if not exists public.miniapp_analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  session_id uuid references public.miniapp_sessions(id) on delete set null,
  event_name text not null,
  page_path text,
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  constraint miniapp_analytics_event_name_check
    check (event_name ~ '^[a-z][a-z0-9_]{1,63}$')
);

create index if not exists miniapp_analytics_events_name_created_idx
  on public.miniapp_analytics_events (event_name, created_at desc);

drop trigger if exists miniapp_event_subscriptions_set_updated_at
  on public.miniapp_event_subscriptions;
create trigger miniapp_event_subscriptions_set_updated_at
  before update on public.miniapp_event_subscriptions
  for each row execute procedure public.set_updated_at();

alter table public.miniapp_consents enable row level security;
alter table public.miniapp_event_subscriptions enable row level security;
alter table public.miniapp_analytics_events enable row level security;

revoke all on public.miniapp_consents from anon, authenticated;
revoke all on public.miniapp_event_subscriptions from anon, authenticated;
revoke all on public.miniapp_analytics_events from anon, authenticated;

grant select, insert, update, delete on public.miniapp_consents to service_role;
grant select, insert, update, delete on public.miniapp_event_subscriptions to service_role;
grant select, insert, update, delete on public.miniapp_analytics_events to service_role;
grant usage, select on sequence public.miniapp_analytics_events_id_seq to service_role;
